# Generated by Django 4.0.4 on 2022-06-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amigos',
            options={'verbose_name': 'Список Друзей', 'verbose_name_plural': 'Списки Друзей'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запросы в Друзья', 'verbose_name_plural': 'Запросы'},
        ),
    ]
