# Generated by Django 4.0.4 on 2022-06-07 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Как звать по паспорту?')),
                ('nick', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomad')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='АвадаКедавра')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Мой путь')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='De donde eres, pendejo?')),
                ('visited', models.CharField(blank=True, max_length=50, null=True, verbose_name='3 последние посещенные страны')),
                ('planning', models.CharField(blank=True, max_length=50, null=True, verbose_name='Куда хочешь поехать?')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Якою мовою розмовляэш?')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('gender', models.CharField(choices=[['male', 'Мужской'], ['female', 'Женский']], default='male', max_length=10, null=True, verbose_name='Пол')),
                ('relationship', models.CharField(choices=[['complicated', 'Все сложно'], ['single', 'Словно Птица в Небесах'], ['meetsmb', 'Есть с кем сходить в кино'], ['married', 'Попал(а) в оковы'], ['soloway', 'Живу с кошкой/собакой']], default='none', max_length=20, verbose_name='Статус отношений')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='На созвоне')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Зареганты',
                'ordering': ['nick'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post', verbose_name='Пост')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
