# Generated by Django 4.0.4 on 2022-06-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Registered User', 'verbose_name_plural': 'Зареганты'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nick',
        ),
    ]
