# Generated by Django 4.0.4 on 2022-06-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_amigos_options_alter_friendrequest_options'),
        ('social', '0003_alter_profile_options_profile_nick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='amigos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigos', to='friend.amigos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.CharField(max_length=30, verbose_name='Как звать по паспорту?'),
        ),
    ]
