# Generated by Django 4.0.4 on 2022-06-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_profile_options_profile_amigos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Как звать по паспорту?'),
        ),
    ]
