# Generated by Django 4.0.4 on 2022-06-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_amigos_options_alter_friendrequest_options'),
        ('social', '0005_alter_profile_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amigos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigos', to='friend.amigos'),
        ),
    ]
